Rework ANSI escapes

diff --git a/tit b/tit
--- a/tit
+++ b/tit
@@ -1,14 +1,24 @@
 #!/bin/bash
 TMPDIR="${TMPDIR:-/tmp}"
-TERMUX_ROOTFS_PATH="$(realpath -- "$HOME/termux-fs")"
-TERMUX_BOOTSTRAP_PATH="$(realpath -- "$TMPDIR/termux-fs.zip")"
+TERMUX_ROOTFS_PATH="$(realpath -- "${HOME}/termux-fs")"
+TERMUX_BOOTSTRAP_PATH="$(realpath -- "${TMPDIR}/termux-fs.zip")"
 TERMUX_APP_PATH="/data/data/com.termux"
-TERMUX_FILES_PATH="$TERMUX_APP_PATH/files"
+TERMUX_FILES_PATH="${TERMUX_APP_PATH}/files"
 TERMUX_32_BIT=false
 TERMUX_PACMAN=false
 
+RED=""
+GREEN=""
+YELLOW=""
+BLUE=""
+MAGENTA=""
+CYAN=""
+BOLD=""
+DIM=""
+DEFAULT=""
+
 info() {
-	printf "\033[36m[!] %b\033[0m\n" "$*"
+	printf "${CYAN}[!] %b${DEFAULT}\n" "$*"
 }
 
 error() {
@@ -17,7 +27,7 @@ error() {
 		EXIT=false
 		shift
 	fi
-	printf "\033[1;31m[x] %b\033[0m\n" "$*" 1>&2
+	printf "${BOLD}${RED}[x] %b${DEFAULT}\n" "$*" 1>&2
 	if [ "$EXIT" = true ]; then
 		exit 1
 	fi
@@ -25,7 +35,7 @@ error() {
 }
 
 ok() {
-	printf "\033[32m[✓] %b\033[0m\n" "$*"
+	printf "${GREEN}[✓] %b${DEFAULT}\n" "$*"
 }
 
 run() {
@@ -42,6 +52,18 @@ run() {
 	fi
 	ok "$ACTION"
 }
+
+if [ -t 1 ] && command -v tput > /dev/null; then
+	RED="$(tput setaf 1)"
+	GREEN="$(tput setaf 2)"
+	YELLOW="$(tput setaf 3)"
+	BLUE="$(tput setaf 4)"
+	MAGENTA="$(tput setaf 5)"
+	CYAN="$(tput setaf 6)"
+	BOLD="$(tput bold)"
+	DIM="$(tput dim)"
+	DEFAULT="$(tput sgr0)"
+fi
 
 unset cleanup
 trap "error -n \"Received SIGINT\"; if [ \"\$(type -t cleanup)\" = \"function\" ]; then run \"Cleaning up\" cleanup; fi; exit 1" INT
@@ -77,7 +99,7 @@ similar() {
 	else:
 	    m = min(map(lambda cmd: (cmd, lev_dist(cmd)), ("install", "login", "remove", "list", "backup", "restore", "help")), key=lambda t: t[1])
 	    if m[1] <= 3:
-	        print(f"    \033[1;31mDo you mean: '{m[0]}'?\033[0m\n")
+	        print(f"    ${BOLD}${RED}Do you mean: '{m[0]}'?${DEFAULT}\n")
 	    else:
 	        print("")
 	EOM
@@ -95,25 +117,25 @@ usage() {
 		error -n "$@" 1>&2
 		printf "\n" 1>&2
 	fi
-	printf "%b\033[0m\n" "\033[1;33mTermux-in-Termux (by marquis-ng)"\
-		"\033[2mAn isolated environment of Termux inside Termux."\
-		"\033[2mGitHub: https://github.com/marquis-ng/termux-in-termux\n"\
-		"\033[1;33mUsage:"\
-		"  \033[32m$PROGNAME \033[22;35mCOMMAND \033[36m{ARGS[]}"\
-		"  \033[32m$PROGNAME \033[22;35m[-h,--help,help]\n"\
-		"\033[1;33mCommands:"\
-		"  \033[35minstall \033[36m[--32-bit | -p,--pacman | --reset]"\
-		"      \033[34mInstall the sandbox."\
-		"  \033[35mlogin \033[36m[--32-bit | -p,--pacman | -b,--bind {DIR | FILE} |\n          -w,--workdir {DIR}] [-- {CMD[]}]"\
-		"      \033[34mLogin the sandbox."\
-		"  \033[35mremove \033[36m[--32-bit | -p,--pacman | -y,--yes]"\
-		"      \033[34mRemove the sandbox."\
-		"  \033[35mlist \033[36m[-i,--installed | -s,--size]"\
-		"      \033[34mShow disk usage for each sandbox."\
-		"  \033[35mbackup \033[36m[--32-bit | -p,--pacman | -f,--force] -o,--output {FILE}"\
-		"      \033[34mBackup the sandbox."\
-		"  \033[35mrestore \033[36m[-y,--yes] -a,--archive {FILE}"\
-		"      \033[34mRestore a backup made by the program." 1>&2
+	printf "%b${DEFAULT}\n" "${BOLD}${YELLOW}Termux-in-Termux (by marquis-ng)"\
+		"${DIM}An isolated environment of Termux inside Termux."\
+		"${DIM}GitHub: https://github.com/marquis-ng/termux-in-termux\n"\
+		"${BOLD}${YELLOW}Usage:"\
+		"  ${GREEN}${PROGNAME} ${MAGENTA}COMMAND ${CYAN}{ARGS[]}"\
+		"  ${GREEN}${PROGNAME} ${MAGENTA}[-h,--help,help]\n"\
+		"${BOLD}${YELLOW}Commands:"\
+		"  ${MAGENTA}install ${CYAN}[--32-bit | -p,--pacman | --reset]"\
+		"      ${BLUE}Install the sandbox."\
+		"  ${MAGENTA}login ${CYAN}[--32-bit | -p,--pacman | -b,--bind {DIR | FILE} |\n          -w,--workdir {DIR}] [-- {CMD[]}]"\
+		"      ${BLUE}Login the sandbox."\
+		"  ${MAGENTA}remove ${CYAN}[--32-bit | -p,--pacman | -y,--yes]"\
+		"      ${BLUE}Remove the sandbox."\
+		"  ${MAGENTA}list ${CYAN}[-i,--installed | -s,--size]"\
+		"      ${BLUE}Show disk usage for each sandbox."\
+		"  ${MAGENTA}backup ${CYAN}[--32-bit | -p,--pacman | -f,--force] -o,--output {FILE}"\
+		"      ${BLUE}Backup the sandbox."\
+		"  ${MAGENTA}restore ${CYAN}[-y,--yes] -a,--archive {FILE}"\
+		"      ${BLUE}Restore a backup made by the program." 1>&2
 	exit "$EXITCODE"
 }
 
@@ -122,7 +144,7 @@ UNAME="$(uname -o)"
 if [ "$UNAME" = "GNU/Linux" ]; then
 	DEPS+=(git)
 elif [ "$UNAME"  != "Android" ]; then
-	error "Unsupported platform: '$UNAME'"
+	error "Unsupported platform: '${UNAME}'"
 fi
 
 if [ "$(id -u)" = 0 ]; then
@@ -131,7 +153,7 @@ fi
 
 for DEP in "${DEPS[@]}"; do
 	if ! command -v "$DEP" > /dev/null; then
-		error "Command not found: '$DEP'"
+		error "Command not found: '${DEP}'"
 	fi
 done
 
@@ -154,7 +176,7 @@ case "$ARCH" in
 		IS64=false
 		;;
 	*)
-		error "Unsupported architecture: $ARCH"
+		error "Unsupported architecture: ${ARCH}"
 		;;
 esac
 
@@ -163,9 +185,9 @@ tit_check_installed() {
 		return 1
 	elif [ "$UNAME" = "Android" ] || [ "$1" = "-n" ]; then
 		return 0
-	elif [ ! -d "$TERMUX_ROOTFS_PATH/system" ]; then
+	elif [ ! -d "${TERMUX_ROOTFS_PATH}/system" ]; then
 		return 1
-	elif [ -f "$TERMUX_ROOTFS_PATH/system/bin/busybox" ]; then
+	elif [ -f "${TERMUX_ROOTFS_PATH}/system/bin/busybox" ]; then
 		return 0
 	fi
 	return 1
@@ -179,10 +201,10 @@ tit_set_vars() {
 	if [ "$TERMUX_PACMAN" = true ]; then
 		FPREFIX="${TERMUX_ROOTFS_PATH%termux*}"
 		FSUFFIX="${TERMUX_ROOTFS_PATH#"$FPREFIX"}"
-		TERMUX_ROOTFS_PATH="$FPREFIX${FSUFFIX/termux/termux-pacman}"
+		TERMUX_ROOTFS_PATH="${FPREFIX}${FSUFFIX/termux/termux-pacman}"
 		FPREFIX="${TERMUX_BOOTSTRAP_PATH%termux*}"
 		FSUFFIX="${TERMUX_BOOTSTRAP_PATH#"$FPREFIX"}"
-		TERMUX_BOOTSTRAP_PATH="$FPREFIX${FSUFFIX/termux/termux-pacman}"
+		TERMUX_BOOTSTRAP_PATH="${FPREFIX}${FSUFFIX/termux/termux-pacman}"
 		SOURCE="termux-pacman/termux-packages"
 	fi
 
@@ -227,9 +249,9 @@ tit_install() {
 		if [ "$RESET" = false ]; then
 			if [ "$UNAME" = "Android" ]; then
 				error "Install destination exists"
-			elif [ ! -d "$TERMUX_ROOTFS_PATH/system" ]; then
+			elif [ ! -d "${TERMUX_ROOTFS_PATH}/system" ]; then
 				tit_install_android_base
-			elif [ ! -f "$TERMUX_ROOTFS_PATH/system/bin/busybox" ]; then
+			elif [ ! -f "${TERMUX_ROOTFS_PATH}/system/bin/busybox" ]; then
 				tit_install_busybox
 			else
 				error "Install destination exists"
@@ -255,10 +277,10 @@ tit_install_bootstrap() {
 			run "Remove Termux bootstrap" rm -rf "$TERMUX_BOOTSTRAP_PATH"
 		fi
 		mkdir -p "$(dirname "$TERMUX_BOOTSTRAP_PATH")"
-		run "Download Termux bootstrap" wget "https://github.com/$SOURCE/releases/latest/download/bootstrap-$BOOTSTRAP_ARCH.zip" -q --show-progress -O "$TERMUX_BOOTSTRAP_PATH"
+		run "Download Termux bootstrap" wget "https://github.com/${SOURCE}/releases/latest/download/bootstrap-${BOOTSTRAP_ARCH}.zip" -q --show-progress -O "$TERMUX_BOOTSTRAP_PATH"
 	fi
 
-	if ! run -n "Verify SHA256 of bootstrap" [ "$(wget -qO- "https://github.com/$SOURCE/releases/latest/download/CHECKSUMS-sha256.txt" | awk "\$1 == \"bootstrap-$BOOTSTRAP_ARCH.zip\" {printf(\$2)}")" =  "$(sha256sum "$TERMUX_BOOTSTRAP_PATH" | awk "{printf(\$1)}")" ]; then
+	if ! run -n "Verify SHA256 of bootstrap" [ "$(wget -qO- "https://github.com/${SOURCE}/releases/latest/download/CHECKSUMS-sha256.txt" | awk "\$1 == \"bootstrap-${BOOTSTRAP_ARCH}.zip\" {printf(\$2)}")" =  "$(sha256sum "$TERMUX_BOOTSTRAP_PATH" | awk "{printf(\$1)}")" ]; then
 		if run "Remove corrupted/expired bootstrap" rm -f "$TERMUX_BOOTSTRAP_PATH"; then
 			info "Restart script"
 			exec "$(realpath -- "$0")" "${ARGS[@]}"
@@ -270,13 +292,13 @@ tit_install_bootstrap() {
 
 	info "Create symlinks"
 	while read -r LINK; do
-		if ! (IFS="←" && read -r SRC DEST <<< "$LINK" && ln -sf "$SRC" "$TERMUX_ROOTFS_PATH/$DEST"); then
+		if ! (IFS="←" && read -r SRC DEST <<< "$LINK" && ln -sf "$SRC" "${TERMUX_ROOTFS_PATH}/${DEST}"); then
 			error "Create symlinks"
 		fi
-	done < "$TERMUX_ROOTFS_PATH/SYMLINKS.txt"
-	ok "Create $(wc -l < "$TERMUX_ROOTFS_PATH/SYMLINKS.txt") symlinks"
-	rm "$TERMUX_ROOTFS_PATH/SYMLINKS.txt"
-	mkdir -p "$TERMUX_ROOTFS_PATH/home" "$TERMUX_ROOTFS_PATH/var/cache"
+	done < "${TERMUX_ROOTFS_PATH}/SYMLINKS.txt"
+	ok "Create $(wc -l < "${TERMUX_ROOTFS_PATH}/SYMLINKS.txt") symlinks"
+	rm "${TERMUX_ROOTFS_PATH}/SYMLINKS.txt"
+	mkdir -p "${TERMUX_ROOTFS_PATH}/home" "${TERMUX_ROOTFS_PATH}/var/cache"
 	if [ "$UNAME" != "GNU/Linux" ]; then
 		exit 0
 	fi
@@ -286,10 +308,10 @@ tit_install_bootstrap() {
 
 tit_install_android_base() {
 	cleanup() {
-		rm -rf "$TERMUX_ROOTFS_PATH/system"
+		rm -rf "${TERMUX_ROOTFS_PATH}/system"
 	}
 
-	local ANDROID_BASE="$TMPDIR/android-base"
+	local ANDROID_BASE="${TMPDIR}/android-base"
 	if [ -d "$ANDROID_BASE" ]; then
 		info "Use cached Android base"
 	else
@@ -312,23 +334,23 @@ tit_install_android_base() {
 
 	case "$ARCH" in
 		aarch64|arm)
-			run "Copy Android base (arm)" cp -r "$ANDROID_BASE/system/arm" "$TERMUX_ROOTFS_PATH/system"
+			run "Copy Android base (arm)" cp -r "${ANDROID_BASE}/system/arm" "${TERMUX_ROOTFS_PATH}/system"
 			;;
 		x86_64|i686)
-			run "Copy Android base (x86)" cp -r "$ANDROID_BASE/system/x86" "$TERMUX_ROOTFS_PATH/system"
+			run "Copy Android base (x86)" cp -r "${ANDROID_BASE}/system/x86" "${TERMUX_ROOTFS_PATH}/system"
 			;;
 	esac
 
-	run "Remove old BusyBox" rm -f "$TERMUX_ROOTFS_PATH/system/bin/busybox"
+	run "Remove old BusyBox" rm -f "${TERMUX_ROOTFS_PATH}/system/bin/busybox"
 	tit_install_busybox
 }
 
 tit_install_busybox() {
 	cleanup() {
-		rm -f "$TERMUX_ROOTFS_PATH/system/bin/busybox"
+		rm -f "${TERMUX_ROOTFS_PATH}/system/bin/busybox"
 	}
 
-	local BUSYBOX="$TMPDIR/busybox-$BOOTSTRAP_ARCH"
+	local BUSYBOX="${TMPDIR}/busybox-${BOOTSTRAP_ARCH}"
 	if [ -f "$BUSYBOX" ]; then
 		info "Use cached BusyBox binary"
 	else
@@ -336,17 +358,17 @@ tit_install_busybox() {
 			run "Remove BusyBox binary" rm -rf "$BUSYBOX"
 		fi
 		mkdir -p "$(dirname "$BUSYBOX")"
-		run "Download new BusyBox binary" wget "https://github.com/marquis-ng/termux-in-termux/raw/main/busybox/busybox-$BOOTSTRAP_ARCH" -q --show-progress -O "$BUSYBOX"
+		run "Download new BusyBox binary" wget "https://github.com/marquis-ng/termux-in-termux/raw/main/busybox/busybox-${BOOTSTRAP_ARCH}" -q --show-progress -O "$BUSYBOX"
 	fi
 
-	if ! run -n "Verify SHA256 of BusyBox binary" [ "$(wget -qO- https://raw.githubusercontent.com/marquis-ng/termux-in-termux/main/busybox/busybox.sha256sum | awk "\$2 == \"busybox-$BOOTSTRAP_ARCH\" {printf(\$1)}")" =  "$(sha256sum "$BUSYBOX" | awk "{printf(\$1)}")" ]; then
+	if ! run -n "Verify SHA256 of BusyBox binary" [ "$(wget -qO- https://raw.githubusercontent.com/marquis-ng/termux-in-termux/main/busybox/busybox.sha256sum | awk "\$2 == \"busybox-${BOOTSTRAP_ARCH}\" {printf(\$1)}")" =  "$(sha256sum "$BUSYBOX" | awk "{printf(\$1)}")" ]; then
 		if run "Remove corrupted BusyBox bianry" rm -f "$BUSYBOX"; then
 			info "Restart script"
 			exec "$(realpath -- "$0")" "${ARGS[@]}"
 		fi
 	fi
-	run "Install new BusyBox" cp "$BUSYBOX" "$TERMUX_ROOTFS_PATH/system/bin/busybox"
-	run "Grant execute permission" chmod +x "$TERMUX_ROOTFS_PATH/system/bin/busybox"
+	run "Install new BusyBox" cp "$BUSYBOX" "${TERMUX_ROOTFS_PATH}/system/bin/busybox"
+	run "Grant execute permission" chmod +x "${TERMUX_ROOTFS_PATH}/system/bin/busybox"
 
 	info "Install applets"
 	for TOOL in "[" "[[" arch ash awk base64 basename bc bunzip2 bzcat bzip2 cal cat chattr chgrp chmod chown chpst chroot cksum\
@@ -359,13 +381,13 @@ tit_install_busybox() {
 			stty swapoff swapon switch_root tac tail tar tee telnet telnetd test time timeout top touch tr true truncate tty ttysize\
 			umount uname unexpand uniq unix2dos unlink unlzma unshare unxz unzip uptime usleep uudecode uuencode vi watch wc wget which who\
 			whoami whois xargs xxd xz xzcat yes zcat zcip; do
-		if ! ln -sf busybox "$TERMUX_ROOTFS_PATH/system/bin/$TOOL"; then
+		if ! ln -sf busybox "${TERMUX_ROOTFS_PATH}/system/bin/${TOOL}"; then
 			error "Install applets"
 		fi
 	done
 	ok "Install applets"
 
-	run "Copy static-dns-hosts.txt" cp "$TMPDIR/android-base/static-dns-hosts.txt" "$TERMUX_ROOTFS_PATH/system/etc/static-dns-hosts.txt"
+	run "Copy static-dns-hosts.txt" cp "${TMPDIR}/android-base/static-dns-hosts.txt" "${TERMUX_ROOTFS_PATH}/system/etc/static-dns-hosts.txt"
 	unset cleanup
 	run -n "Update static DNS" "$(realpath -- "$0")" login -- /system/bin/update-static-dns
 }
@@ -417,10 +439,7 @@ tit_login() {
 	if ! tit_check_installed; then
 		error "System not installed"
 	fi
-	local CMDLINE=(proot --kill-on-exit -r "$TERMUX_ROOTFS_PATH" -w "$TERMUX_FILES_PATH/home")
-	if [ "${#TERMUX_PROOT_ARGS[@]}" != 0 ]; then
-		CMDLINE+=("${TERMUX_PROOT_ARGS[@]}")
-	fi
+	local CMDLINE=(proot --kill-on-exit -r "$TERMUX_ROOTFS_PATH" -w "${TERMUX_FILES_PATH}/home" "${TERMUX_PROOT_ARGS[@]}")
 
 	BINDS=(/dev /proc /sys /sdcard "${PREFIX:-/usr}/..:/host-rootfs")
 	if [ "$UNAME" = "Android" ]; then
@@ -432,33 +451,33 @@ tit_login() {
 		fi
 	done
 
-	CMDLINE+=(-b "$TERMUX_ROOTFS_PATH:$TERMUX_FILES_PATH/usr"
-		-b "$TERMUX_ROOTFS_PATH/home:$TERMUX_FILES_PATH/home"
-		-b "$TERMUX_ROOTFS_PATH/var/cache:$TERMUX_APP_PATH/cache"
+	CMDLINE+=(-b "${TERMUX_ROOTFS_PATH}:${TERMUX_FILES_PATH}/usr"
+		-b "${TERMUX_ROOTFS_PATH}/home:${TERMUX_FILES_PATH}/home"
+		-b "${TERMUX_ROOTFS_PATH}/var/cache:${TERMUX_APP_PATH}/cache"
 	)
 
-	CMDLINE+=("$TERMUX_FILES_PATH/usr/bin/env" -i
-		"HOME=$TERMUX_FILES_PATH/home"
-		"PATH=$TERMUX_FILES_PATH/usr/bin"
-		"PREFIX=$TERMUX_FILES_PATH/usr"
-		"TMPDIR=$TERMUX_FILES_PATH/usr/tmp"
+	CMDLINE+=("${TERMUX_FILES_PATH}/usr/bin/env" -i
+		"HOME=${TERMUX_FILES_PATH}/home"
+		"PATH=${TERMUX_FILES_PATH}/usr/bin"
+		"PREFIX=${TERMUX_FILES_PATH}/usr"
+		"TMPDIR=${TERMUX_FILES_PATH}/usr/tmp"
 		"ANDROID_DATA=/data"
 		"ANDROID_ROOT=/system"
 		"EXTERNAL_STORAGE=/sdcard"
-		"LD_PRELOAD=$TERMUX_FILES_PATH/usr/lib/libtermux-exec.so"
-		"LD_LIBRARY_PATH=$TERMUX_FILES_PATH/usr/lib"
+		"LD_PRELOAD=${TERMUX_FILES_PATH}/usr/lib/libtermux-exec.so"
+		"LD_LIBRARY_PATH=${TERMUX_FILES_PATH}/usr/lib"
 		"TERM=${TERM=-xterm-256color}"
 		"COLORTERM=${TERM=-truecolor}"
 		"LANG=${LANG=-en_US.UTF-8}"
-		"TERMUX_APK_RELEASE=$TERMUX_APK_RELEASE"
-		"TERMUX_VERSION=$TERMUX_VERSION"
+		"TERMUX_APK_RELEASE=${TERMUX_APK_RELEASE}"
+		"TERMUX_VERSION=${TERMUX_VERSION}"
 	)
 	if [ -n "${TERMUX_API_VERSION}" ]; then
-		CMDLINE+=("TERMUX_API_VERSION=$TERMUX_API_VERSION")
+		CMDLINE+=("TERMUX_API_VERSION=${TERMUX_API_VERSION}")
 	fi
 
 	if [ "$INTERACTIVE" = true ]; then
-		CMDLINE+=("$TERMUX_FILES_PATH/usr/bin/login")
+		CMDLINE+=("${TERMUX_FILES_PATH}/usr/bin/login")
 	else
 		if [ "$#" = 0 ]; then
 			usage "Missing parameter: '--'"
@@ -534,12 +553,12 @@ tit_list() {
 		fi
 		if tit_check_installed; then
 			if [ "$SHOW_SIZE" = true ]; then
-				printf "\033[32m%s\033[0m \033[34m%s\033[0m\n" "$(basename "$TERMUX_ROOTFS_PATH")" "$(du -sh "$TERMUX_ROOTFS_PATH" 2>/dev/null | awk "{printf(\$1)}")"
+				printf "${GREEN}%s${DEFAULT} ${BLUE}%s${DEFAULT}\n" "$(basename "$TERMUX_ROOTFS_PATH")" "$(du -sh "$TERMUX_ROOTFS_PATH" 2>/dev/null | awk "{printf(\$1)}")"
 			else
-				printf "\033[32m%s\033[0m\n" "$(basename "$TERMUX_ROOTFS_PATH")"
+				printf "${GREEN}%s${DEFAULT}\n" "$(basename "$TERMUX_ROOTFS_PATH")"
 			fi
 		elif [ "$ONLY_INSTALLED" = false ]; then
-			printf "\033[31m%s\033[0m\n" "$(basename "$TERMUX_ROOTFS_PATH")"
+			printf "${RED}%s${DEFAULT}\n" "$(basename "$TERMUX_ROOTFS_PATH")"
 		fi
 	done
 }
@@ -590,7 +609,7 @@ tit_backup() {
 	fi
 
 	info "Generate metadata"
-	local METADATA="$TMPDIR/tit_metadata"
+	local METADATA="${TMPDIR}/tit_metadata"
 	printf "%s=\"%s\"\n" "TERMUX_32_BIT" "$TERMUX_32_BIT"\
 		"TERMUX_PACMAN" "$TERMUX_PACMAN"\
 		"BACKUP_HOST_ARCH" "$ARCH"\
@@ -605,7 +624,7 @@ tit_backup() {
 	if ! tar -cf "$DEST" -C "$(dirname "$METADATA")" "$(basename "$METADATA")" -C "$(dirname "$TERMUX_ROOTFS_PATH")" "$(basename "$TERMUX_ROOTFS_PATH")" &>/dev/null; then
 			error "Backup sandbox"
 		fi
-	ok "Backup sandbox to '$DEST'"
+	ok "Backup sandbox to '${DEST}'"
 }
 
 tit_restore() {
@@ -644,9 +663,9 @@ tit_restore() {
 	# shellcheck source=/dev/null
 	. <(tar -xOf "$ARCHIVE" tit_metadata 2>/dev/null || printf "error \"Broken archive\"\n")
 	if [ "$ARCH" != "$BACKUP_HOST_ARCH" ]; then
-		error "Device architectures mismatch ('$ARCH' != '$BACKUP_HOST_ARCH')"
+		error "Device architectures mismatch ('${ARCH}' != '${BACKUP_HOST_ARCH}')"
 	elif [ "$UNAME" != "$BACKUP_HOST_UNAME" ]; then
-		error "Operating systems mismatch ('$UNAME' != '$BACKUP_HOST_UNAME')"
+		error "Operating systems mismatch ('${UNAME}' != '${BACKUP_HOST_UNAME}')"
 	fi
 	tit_set_vars
 
