Error if no command provided after '--'

diff --git a/tit b/tit
--- a/tit
+++ b/tit
@@ -94,8 +94,8 @@ tit_set_vars() {
 	SOURCE="termux/termux-packages"
 	if [ "$TERMUX_PACMAN" = true ]; then
 		PREFIX="${TERMUX_ROOTFS_PATH%termux*}"
-	        SUFFIX="${TERMUX_ROOTFS_PATH#"$PREFIX"}"
-	        TERMUX_ROOTFS_PATH="$PREFIX${SUFFIX/termux/termux-pacman}"
+		SUFFIX="${TERMUX_ROOTFS_PATH#"$PREFIX"}"
+		TERMUX_ROOTFS_PATH="$PREFIX${SUFFIX/termux/termux-pacman}"
 		PREFIX="${TERMUX_BOOTSTRAP_PATH%termux*}"
 		SUFFIX="${TERMUX_BOOTSTRAP_PATH#"$PREFIX"}"
 		TERMUX_BOOTSTRAP_PATH="$PREFIX${SUFFIX/termux/termux-pacman}"
@@ -103,16 +103,15 @@ tit_set_vars() {
 	fi
 
 	if [ "$TERMUX_32_BIT" = true ]; then
-		if [ "$IS64" = true ]; then
-			TERMUX_ROOTFS_PATH+="32"
-			TERMUX_BOOTSTRAP_PATH="${TERMUX_BOOTSTRAP_PATH%.zip}32.zip"
-			if [ "$ARCH" = "aarch64" ]; then
-				ARCH="arm"
-			else
-				ARCH="i686"
-			fi
-		else
+		if [ "$IS64" != true ]; then
 			error "'--32-bit' can only be used on 32-bit systems."
+		fi
+		TERMUX_ROOTFS_PATH+="32"
+		TERMUX_BOOTSTRAP_PATH="${TERMUX_BOOTSTRAP_PATH%.zip}32.zip"
+		if [ "$ARCH" = "aarch64" ]; then
+			ARCH="arm"
+		else
+			ARCH="i686"
 		fi
 	fi
 }
@@ -140,72 +139,72 @@ tit_install() {
 
 	if tit_check_installed && [ "$RESET" = false ]; then
 		error "System is already installed."
-	else
-		if tit_check_installed; then
-			local PRESERVE=true
-			tit_remove
-		fi
-		if [ -f "$TERMUX_BOOTSTRAP_PATH" ]; then
-			info "Using downloaded Termux bootstrap."
-		else
-			if [ -e "$TERMUX_BOOTSTRAP_PATH" ]; then
-				rm -rf "$TERMUX_BOOTSTRAP_PATH"
-			fi
-			info "Downloading Termux bootstrap..."
-			mkdir -p "$(dirname "$TERMUX_BOOTSTRAP_PATH")"
-			if wget "https://github.com/$SOURCE/releases/latest/download/bootstrap-$ARCH.zip" -q --show-progress -O "$TERMUX_BOOTSTRAP_PATH"; then
-				info "Termux bootstrap downloaded."
-			else
-				error "Failed to download Termux bootstrap."
-			fi
-		fi
-
-		info "Verifying integrity of bootstrap..."
-		# shellcheck disable=SC2155
-		local EXSHA="$(wget -qO- https://github.com/$SOURCE/releases/latest/download/bootstraps.sha256sum | awk "\$2 == \"bootstrap-$ARCH.zip\" {printf(\$1)}")"
-		# shellcheck disable=SC2155
-		local RSHA="$(sha256sum "$TERMUX_BOOTSTRAP_PATH" | awk "{printf(\$1)}")"
-		if [ "$EXSHA" == "$RSHA" ]; then
-			info "SHA256 matches."
-		else
-			info "\033[31mSHA256 checksums do not match."
-			info "\033[31mExpected: $EXSHA"
-			info "\033[31mFound: $RSHA"
-			if rm -f "$TERMUX_BOOTSTRAP_PATH"; then
-				info "Removed corrupted/expired bootstrap. Rerunning script..."
-				exec "$(realpath -- "$0")" "${ARGS[@]}"
-			else
-				error "Failed to remove corrupted/outdated bootstrap. Abort."
-			fi
-		fi
-
-		mkdir -p "$TERMUX_ROOTFS_PATH"
-		if ! cd "$TERMUX_ROOTFS_PATH"; then
-			error "Failed to change directory. Abort."
-		fi
-		info "Extracting Termux bootstrap..."
-		if unzip -q "$TERMUX_BOOTSTRAP_PATH"; then
-			info "Termux bootstrap extracted."
-		else
-			error "Failed to extract Termux bootstrap."
-		fi
-
-		info "Creating symlinks..."
-		while read -r LINK; do
-			(IFS="←"; read -r SRC DEST <<< "$LINK"; ln -sf "$SRC" "$DEST")
-		done < SYMLINKS.txt
-		info "Created $(wc -l < SYMLINKS.txt) symlinks."
-		rm SYMLINKS.txt
-
-		info "Making common directories..."
-		mkdir -p home var/cache
-		info "Directories are successfully made."
-		info "Install finished without errors!"
 	fi
+	if tit_check_installed; then
+		local PRESERVE=true
+		tit_remove
+	fi
+	if [ -f "$TERMUX_BOOTSTRAP_PATH" ]; then
+		info "Using downloaded Termux bootstrap."
+	else
+		if [ -e "$TERMUX_BOOTSTRAP_PATH" ]; then
+			rm -rf "$TERMUX_BOOTSTRAP_PATH"
+		fi
+		info "Downloading Termux bootstrap..."
+		mkdir -p "$(dirname "$TERMUX_BOOTSTRAP_PATH")"
+		if wget "https://github.com/$SOURCE/releases/latest/download/bootstrap-$ARCH.zip" -q --show-progress -O "$TERMUX_BOOTSTRAP_PATH"; then
+			info "Termux bootstrap downloaded."
+		else
+			error "Failed to download Termux bootstrap."
+		fi
+	fi
+
+	info "Verifying integrity of bootstrap..."
+	# shellcheck disable=SC2155
+	local EXSHA="$(wget -qO- https://github.com/$SOURCE/releases/latest/download/bootstraps.sha256sum | awk "\$2 == \"bootstrap-$ARCH.zip\" {printf(\$1)}")"
+	# shellcheck disable=SC2155
+	local RSHA="$(sha256sum "$TERMUX_BOOTSTRAP_PATH" | awk "{printf(\$1)}")"
+	if [ "$EXSHA" == "$RSHA" ]; then
+		info "SHA256 matches."
+	else
+		info "\033[31mSHA256 checksums do not match."
+		info "\033[31mExpected: $EXSHA"
+		info "\033[31mFound: $RSHA"
+		if rm -f "$TERMUX_BOOTSTRAP_PATH"; then
+			info "Removed corrupted/expired bootstrap. Rerunning script..."
+			exec "$(realpath -- "$0")" "${ARGS[@]}"
+		else
+			error "Failed to remove corrupted/outdated bootstrap. Abort."
+		fi
+	fi
+
+	mkdir -p "$TERMUX_ROOTFS_PATH"
+	if ! cd "$TERMUX_ROOTFS_PATH"; then
+		error "Failed to change directory. Abort."
+	fi
+	info "Extracting Termux bootstrap..."
+	if unzip -q "$TERMUX_BOOTSTRAP_PATH"; then
+		info "Termux bootstrap extracted."
+	else
+		error "Failed to extract Termux bootstrap."
+	fi
+
+	info "Creating symlinks..."
+	while read -r LINK; do
+		(IFS="←"; read -r SRC DEST <<< "$LINK"; ln -sf "$SRC" "$DEST")
+	done < SYMLINKS.txt
+	info "Created $(wc -l < SYMLINKS.txt) symlinks."
+	rm SYMLINKS.txt
+
+	info "Making common directories..."
+	mkdir -p home var/cache
+	info "Directories are successfully made."
+	info "Install finished without errors!"
 }
 
 tit_login() {
 	local TERMUX_PROOT_ARGS=()
+	local INTERACTIVE=true
 	while [ "$#" != 0 ]; do
 		case "$1" in
 			--32-bit)
@@ -217,17 +216,16 @@ tit_login() {
 			-b|--bind)
 				if [ "$#" = 1 ]; then
 					usage "'--bind' requires an argument."
-				else
-					shift
-					if [ -z "$1" ]; then
-						usage "Please do not pass empty arguments."
-					else
-						TERMUX_PROOT_ARGS+=("-b" "$1")
-					fi
 				fi
+				shift
+				if [ -z "$1" ]; then
+					usage "Please do not pass empty arguments."
+				fi
+				TERMUX_PROOT_ARGS+=("-b" "$1")
 				;;
 			--)
 				shift
+				INTERACTIVE=false
 				break
 				;;
 			*)
@@ -238,53 +236,55 @@ tit_login() {
 	done
 	tit_set_vars
 
-	if tit_check_installed; then
-		local CMDLINE=(proot --kill-on-exit -r "$TERMUX_ROOTFS_PATH" -w "$TERMUX_FILES_PATH/home")
-		if [ "${#TERMUX_PROOT_ARGS[@]}" != 0 ]; then
-			CMDLINE+=("${TERMUX_PROOT_ARGS[@]}")
-		fi
-
-		for DIR in /dev /proc /sys /system /vendor /apex /sdcard "$PREFIX/..:/host-rootfs"; do
-			if [ -d "$DIR" ] || printf "%s\n" "$DIR" | grep -q "com\.termux"; then
-				CMDLINE+=(-b "$DIR")
-			fi
-		done
-
-		CMDLINE+=(-b "$TERMUX_ROOTFS_PATH:$TERMUX_FILES_PATH/usr"
-			-b "$TERMUX_ROOTFS_PATH/home:$TERMUX_FILES_PATH/home"
-			-b "$TERMUX_ROOTFS_PATH/var/cache:$TERMUX_APP_PATH/cache"
-		)
-
-		CMDLINE+=("$TERMUX_FILES_PATH/usr/bin/env" -i
-			"HOME=$TERMUX_FILES_PATH/home"
-			"PATH=$TERMUX_FILES_PATH/usr/bin"
-			"PREFIX=$TERMUX_FILES_PATH/usr"
-			"TMPDIR=$TERMUX_FILES_PATH/usr/tmp"
-			"ANDROID_DATA=/data"
-			"ANDROID_ROOT=/system"
-			"EXTERNAL_STORAGE=/sdcard"
-			"LD_PRELOAD=$TERMUX_FILES_PATH/usr/lib/libtermux-exec.so"
-			"TERM=${TERM=-xterm-256color}"
-			"COLORTERM=${TERM=-truecolor}"
-			"LANG=${LANG=-en_US.UTF-8}"
-			"TERMUX_APK_RELEASE=$TERMUX_APK_RELEASE"
-			"TERMUX_VERSION=$TERMUX_VERSION"
-		)
-		if [ -n "${TERMUX_API_VERSION}" ]; then
-			CMDLINE+=("TERMUX_API_VERSION=$TERMUX_API_VERSION")
-		fi
-
-		if [ "$#" = 0 ]; then
-			CMDLINE+=("$TERMUX_FILES_PATH/usr/bin/login")
-		else
-			CMDLINE+=("$@")
-		fi
-
-		unset LD_PRELOAD
-		exec "${CMDLINE[@]}"
-	else
+	if ! tit_check_installed; then
 		error "System is not installed."
 	fi
+	local CMDLINE=(proot --kill-on-exit -r "$TERMUX_ROOTFS_PATH" -w "$TERMUX_FILES_PATH/home")
+	if [ "${#TERMUX_PROOT_ARGS[@]}" != 0 ]; then
+		CMDLINE+=("${TERMUX_PROOT_ARGS[@]}")
+	fi
+
+	for DIR in /dev /proc /sys /system /vendor /apex /sdcard "$PREFIX/..:/host-rootfs"; do
+		if [ -d "$DIR" ] || printf "%s\n" "$DIR" | grep -q "com\.termux"; then
+			CMDLINE+=(-b "$DIR")
+		fi
+	done
+
+	CMDLINE+=(-b "$TERMUX_ROOTFS_PATH:$TERMUX_FILES_PATH/usr"
+		-b "$TERMUX_ROOTFS_PATH/home:$TERMUX_FILES_PATH/home"
+		-b "$TERMUX_ROOTFS_PATH/var/cache:$TERMUX_APP_PATH/cache"
+	)
+
+	CMDLINE+=("$TERMUX_FILES_PATH/usr/bin/env" -i
+		"HOME=$TERMUX_FILES_PATH/home"
+		"PATH=$TERMUX_FILES_PATH/usr/bin"
+		"PREFIX=$TERMUX_FILES_PATH/usr"
+		"TMPDIR=$TERMUX_FILES_PATH/usr/tmp"
+		"ANDROID_DATA=/data"
+		"ANDROID_ROOT=/system"
+		"EXTERNAL_STORAGE=/sdcard"
+		"LD_PRELOAD=$TERMUX_FILES_PATH/usr/lib/libtermux-exec.so"
+		"TERM=${TERM=-xterm-256color}"
+		"COLORTERM=${TERM=-truecolor}"
+		"LANG=${LANG=-en_US.UTF-8}"
+		"TERMUX_APK_RELEASE=$TERMUX_APK_RELEASE"
+		"TERMUX_VERSION=$TERMUX_VERSION"
+	)
+	if [ -n "${TERMUX_API_VERSION}" ]; then
+		CMDLINE+=("TERMUX_API_VERSION=$TERMUX_API_VERSION")
+	fi
+
+	if [ "$INTERACTIVE" = true ]; then
+		CMDLINE+=("$TERMUX_FILES_PATH/usr/bin/login")
+	else
+		if [ "$#" = 0 ]; then
+			usage "'--' must be followed by a command."
+		fi
+		CMDLINE+=("$@")
+	fi
+
+	unset LD_PRELOAD
+	exec "${CMDLINE[@]}"
 }
 
 tit_remove() {
@@ -308,27 +308,25 @@ tit_remove() {
 	done
 	tit_set_vars
 
-	if tit_check_installed; then
-		local KEY
-		if [ "$ASK" = true ]; then
-			info "Remove system ($TERMUX_ROOTFS_PATH)?"
-			info "Press 'n' to abort in 5 seconds."
-			read -rsn1 -t5 KEY
-		else
-			KEY="Y"
-		fi
-		if [ "${KEY^^}" = "N" ]; then
-			error "Abort."
-		else
-			info "Removing system..."
-			if rm -rf "$TERMUX_ROOTFS_PATH"; then
-				info "System is successfully removed."
-			else
-				error "Failed to remove system."
-			fi
-		fi
-	else
+	if ! tit_check_installed; then
 		error "System is not installed."
+	fi
+	local KEY
+	if [ "$ASK" = true ]; then
+		info "Remove system ($TERMUX_ROOTFS_PATH)?"
+		info "Press 'n' to abort in 5 seconds."
+		read -rsn1 -t5 KEY
+	else
+		KEY="Y"
+	fi
+	if [ "${KEY^^}" = "N" ]; then
+		error "Abort."
+	fi
+	info "Removing system..."
+	if rm -rf "$TERMUX_ROOTFS_PATH"; then
+		info "System is successfully removed."
+	else
+		error "Failed to remove system."
 	fi
 }
 
